### ISSUE TITLE
Only reload new models? 

### ISSUE THREAD

**Issue by marcusklaas** [vaitech/Velox#2]
The following snippet seems to reload the model regardless of whether a new version is available:
```
model.reload(
    prefix=model_path,
    scheduled=True,
    minutes=30
)
```
Is this the intended behaviour? If so, is there a way to reload the model only when a more recent version is available?

**Comment by marcusklaas** [comment]
The issue may be here: https://github.com/vaitech/Velox/blob/5d38e61875191259073a94e2c967c319c4de5576/velox/obj.py#L365-L366

The current hash isn't passed to the load and therefore the load is never skipped.

**Comment by lukedeo** [comment]
Fixed, see https://github.com/vaitech/Velox/pull/3
